manifest = "94f29faa78112a0223d90bb04bb11846c669f9053ecc9517bd994724932891f9"

[[dependency]]
package = "github.com/buckaroo-pm/boost-atomic"
target = "//:atomic"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-lexical_cast"
target = "//:lexical-cast"

[[dependency]]
package = "github.com/buckaroo-pm/boost-multiprecision"
target = "//:multiprecision"

[[dependency]]
package = "github.com/buckaroo-pm/boost-predef"
target = "//:predef"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart-ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-test"
target = "//:test"

[[dependency]]
package = "github.com/buckaroo-pm/boost-ublas"
target = "//:ublas"

[lock."github.com/buckaroo-pm/boost-algorithm"]
versions = [ "1.59.0" ]
revision = "3f3b958482960f6ed5bb9c01406fe3a255b454b6"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "1.59.0" ]
revision = "2f38fe2c0c5b69b59cd6a474cd9a87e604b82e0a"

[lock."github.com/buckaroo-pm/boost-array"]
versions = [ "1.59.0" ]
revision = "67cb7c79f2d4679eb674a4928ccba9d9ee804855"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.59.0" ]
revision = "ae3f1d72ea2051a7eac680375e191e5337424cc6"

[lock."github.com/buckaroo-pm/boost-atomic"]
versions = [ "1.59.0" ]
revision = "09418d42e1128b54af87c758c7411734ea1cda54"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.59.0" ]
revision = "70a95ef1a92a036ffbe9278d40b0e35c14b6d767"

[lock."github.com/buckaroo-pm/boost-chrono"]
versions = [ "1.59.0" ]
revision = "5c0210d65bde6ccbe0d4878288234a5f86dbc8e7"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "1.59.0" ]
revision = "6455e987cc9f6a2260b9ddbcf547fceb0a41f6f7"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.59.0" ]
revision = "da25bbd04095a842f940e97d82d7d6fd01e829a8"

[lock."github.com/buckaroo-pm/boost-container"]
versions = [ "1.59.0" ]
revision = "2ee739cd5e6419027e0424ebb3cac568d54efde8"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.59.0" ]
revision = "1e8774ff13d17b27725c797cdd676776aa6f104d"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.59.0" ]
revision = "78272c16dee9ecf4ab430cd62d470197b4bc3db8"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.59.0" ]
revision = "b3b0f9ff58d766c2efb38924a7944ecc0b2d965f"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.59.0" ]
revision = "84d54634d766e6f309af8e5bdf3271deec2ce59f"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.59.0" ]
revision = "fa7548e829416bdb30796ddbd87b1084f6f756f1"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.59.0" ]
revision = "96620f3df10cfea0265694e7d63daff9d751f234"

[lock."github.com/buckaroo-pm/boost-functional"]
versions = [ "1.59.0" ]
revision = "93f17e8d4d028328aa210b0020662bcf4e4265d9"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.59.0" ]
revision = "752c76255d804ee37560831710f11e8487f4df71"

[lock."github.com/buckaroo-pm/boost-intrusive"]
versions = [ "1.59.0" ]
revision = "beaa4d6c5a74fdf296cb02b94089b76e9ca011bb"

[lock."github.com/buckaroo-pm/boost-io"]
versions = [ "1.59.0" ]
revision = "c0a2a32e9778dfaaa260d04fd626188b5a9bc7e4"

[lock."github.com/buckaroo-pm/boost-iterator"]
versions = [ "1.59.0" ]
revision = "c204c01b6efd58439a5c521a655576cf7a168ff9"

[lock."github.com/buckaroo-pm/boost-lexical_cast"]
versions = [ "1.59.0" ]
revision = "ee61302b465ebb0f8665debe3834118b0891e196"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.59.0" ]
revision = "caa53417aa219b8123146cba46bf79907d49dc53"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.59.0" ]
revision = "3708e9a524ffae7d4ce87590d928aba5ac016878"

[lock."github.com/buckaroo-pm/boost-multiprecision"]
versions = [ "1.59.0" ]
revision = "cb0c878c9ef74eaf4d06ad72dbed0c8e65882b80"

[lock."github.com/buckaroo-pm/boost-numeric_conversion"]
versions = [ "1.59.0" ]
revision = "5518d133802fe5666ddd00033267f7e0668ec1a6"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.59.0" ]
revision = "96e75492eceedee96f94452adc9f0e2b90b8af76"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.59.0" ]
revision = "992e8e442e6d5f602fe8933e3e01fab13f39ee49"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.59.0" ]
revision = "4f7b4c1196b34350a93abfc460b5a27ec2c50e9f"

[lock."github.com/buckaroo-pm/boost-range"]
versions = [ "1.59.0" ]
revision = "75e279ae59e515bbba646ed7312ddd05e1947580"

[lock."github.com/buckaroo-pm/boost-ratio"]
versions = [ "1.59.0" ]
revision = "d5e38a48dfcb791d315f5cd759094119ea46a214"

[lock."github.com/buckaroo-pm/boost-rational"]
versions = [ "1.59.0" ]
revision = "476084c516b59c429304a04a69ae826a34d39a2b"

[lock."github.com/buckaroo-pm/boost-regex"]
versions = [ "1.59.0" ]
revision = "57b2cd966e461f8082cd2433a9619195c06daf5d"

[lock."github.com/buckaroo-pm/boost-serialization"]
versions = [ "1.59.0" ]
revision = "a315900ede54e248313ab54a5c6e83608aebdaed"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.59.0" ]
revision = "efb4f3af04183227659a08d91df4b3402692f947"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.59.0" ]
revision = "5eb386bad4597b39ff2931f754d2a95b90820f0c"

[lock."github.com/buckaroo-pm/boost-system"]
versions = [ "1.59.0" ]
revision = "b0fa9f062aad54056da33d732a79feb563197bc0"

[lock."github.com/buckaroo-pm/boost-test"]
versions = [ "1.59.0" ]
revision = "cc2b39f39db0561b46dc892f47cdfee3687af015"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.59.0" ]
revision = "dc5ca7bc204decdc5fe2729083c8fd6b45c4e13f"

[lock."github.com/buckaroo-pm/boost-timer"]
versions = [ "1.59.0" ]
revision = "af013f063d5a3abec8b0decf2b477075ac98a4aa"

[lock."github.com/buckaroo-pm/boost-tuple"]
versions = [ "1.59.0" ]
revision = "4c64663d6ecc3b85f79cc0db15653e69e989286f"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.59.0" ]
revision = "98e970ce0b4cc56885eaa08412df8362ac88e2e4"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.59.0" ]
revision = "d3e40c7e8392b5d89a9900063b33d48fe1ffe35e"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.59.0" ]
revision = "d8686f1c2e467127ae409fc36156ec9d73847e1c"

[lock."github.com/buckaroo-pm/boost-ublas"]
versions = [ "1.59.0" ]
revision = "27f3f24e6e96461ab714b58490fc82e79bfa532d"

[lock."github.com/buckaroo-pm/boost-unordered"]
versions = [ "1.59.0" ]
revision = "edb535829567e91fe5f53b5156bd4ea9d17f3601"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.59.0" ]
revision = "eeb2b94a309d25d01de5864e0f5cad8274cac4af"

[lock."github.com/buckaroo-pm/boost-winapi"]
versions = [ "1.59.0" ]
revision = "d9bc6437199302b76be14b332cccf3c82d3b7355"

[lock."github.com/buckaroo-pm/icu4c"]
versions = [ "branch=master" ]
revision = "2bfbe715e2c1cd41e301b6a67fd50ae54273a504"
